version: "3.9"  # optional since v1.27.0
services:
  app:
    build:
      context: .
    container_name: my-app
  rstudio:
    image: "rocker/verse:latest"
    ports:
      - 8787:8787
    volumes:
      - ./app:/app
    container_name: rstudio-container
  datascience-notebook:
    image: jupyter/datascience-notebook
    volumes:
      - ./app:/app
    ports:
      - 8888:8888
    volumes:
      - ./app:/app
    container_name:      datascience-notebook-container
